name: CI for Python Selenium Tests

on:
  push:
    branches:
      - "*"  # Run the pipeline on all branches
  pull_request:
    branches:
      - "*"  # Run the pipeline on all pull requests
  schedule:
    - cron: '0 13 * * *'  # Run every day at 13:00 UTC

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      HEADLESS: false
      BASE_URL: https://portal.dev.uksouth.vocovo.com/
      PROD_UK_BASE_URL: https://portal.vocovo.com/
      PROD_US_BASE_URL: https://portal.us.vocovo.com/
      USERNAME_FALSE: forgot_pass_user4082@vocovo.com
      ADMIN_USERNAME: qa-testing@vocovo.com
      ADMIN_PASSWORD: vocovoT3st!ng@utomation
      QASE_API_TOKEN: ae98bb7b27408a4c8c7be2651e35b061d55f719c00a7f31489e005073606961a
      QASE_PROJECT_CODE: CE

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install pipenv
        pipenv install --dev

    - name: Run smoke tests with verbosity
      run: |
        xvfb-run -a pipenv run pytest -m "portaluksmoketests" -v
